[package]
name = "JPlayer"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
ffmpeg-sys-next = "8.1.0"
bytemuck = { version = "1.25.0", features = ["derive"] }
glfw = "0.55"
gl = "0.14"
nanovg-sys = {
    path = "./nanovg-sys",
    default-features = false,
    features = ["gl3"]
}
cpal = "0.17.3"
reqwest = { version = "0.11", features = ["blocking"] }
base64 = "0.22.1"
json = "0.12.4"
libwebp = { version = "0.1.2", features = ["0_6"] }
libc = "0.2.186"
mlua = { version = "0.11.6", features = ["lua55"] }
crc32fast = "1.5.0"